services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - ./djangoapp:/djangoapp
      - staticdata:/data/web/static
      - mediadata:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - fila_api

  fila_api:
    container_name: fila_api
    build:
      context: ./fila-api-hulw
    env_file:
      - ./dotenv_files/.env
    ports:
      - "9000:9000"
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hulw_db
      - POSTGRES_USER=hulw_user
      - POSTGRES_PASSWORD=hulw_senha_segura_123

volumes:
  staticdata:
  mediadata:
  pgdata: